# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  symfony-checking-env-file-and-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.4'
    - uses: actions/checkout@v4
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

  symfony-checking-dockerized-db:
    runs-on: ubuntu-latest
    needs: symfony-checking-env-file-and-dependencies

    steps:
    - uses: actions/checkout@v4
    - name: Building the container
      run: docker compose build
    - name: Running the container
      run: docker compose up -d
    - name: Listing the volumes
      run: docker volume ls
    - name: Inspecting the volumes
      run: docker volume inspect telecine_telecine-volume

  symfony-unit-feature-tests:
    runs-on: ubuntu-latest
    needs: symfony-checking-dockerized-db
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_DATABASE: db_telecine_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3307

    steps:

    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.4'
    - uses: actions/checkout@v4
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Migrating data into DB
      env:
        DATABASE_URL: mysql://root:root@mysql:3307/db_telecine_test?serverVersion=11.8.2-MariaDB&charset=utf8mb4
      run: php bin/console doctrine:migrations:migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --colors --display-errors
